apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-example
  namespace: articles
spec:
  selector:
    matchLabels:
      app: consumer-example
  replicas: 1
  template:
    metadata:
      namespace: consumer-example
      labels:
        app: consumer-example
    spec:
      containers:
        - name: consumer-example
          image: vertxzookeeperexample:v1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: DEPLOYMENT_TYPE
              value: "consumer"
            - name: namespace
              value: "consumer"
            - name: port
              value: "8080"
            - name: host
              value: "consumer-service"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  namespace: articles
spec:
  type: ClusterIP
  selector:
    app: producer-example
  ports:
    - name: java-app
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: jvm-stats
      port: 1099
      targetPort: 1099
      protocol: TCP
