apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-example
  namespace: articles
spec:
  selector:
    matchLabels:
      app: producer-example
  replicas: 1
  template:
    metadata:
      namespace: producer-example
      labels:
        app: producer-example
    spec:
      containers:
        - name: producer-example
          image: vertxzookeeperexample:v1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: DEPLOYMENT_TYPE
              value: "producer"
            - name: namespace
              value: "producer"
            - name: port
              value: "8080"
            - name: host
              value: "producer-service"
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: articles
spec:
  type: ClusterIP
  selector:
    app: producer-example
  ports:
    - name: java-app
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: jvm-stats
      port: 1099
      targetPort: 1099
      protocol: TCP
